import tomllib

from support import HermeticTest

from lemmings import agents
from lemmings.gitutil import HelperError

TEAM = {
    "deepseek": {"role": "worker", "host": "codex", "profile": "byteplus", "model": "deepseek-v4-pro",
                 "use": "Routine implementation", "default": True, "escalateTo": "luna-max"},
    "luna-max": {"role": "worker", "host": "codex", "model": "gpt-5.6-luna", "effort": "max",
                 "use": "Hard changes", "escalateTo": "opus-worker"},
    "opus-worker": {"role": "worker", "host": "claude", "model": "opus"},
    "sol": {"role": "reviewer", "host": "codex", "model": "gpt-5.6-sol", "effort": "high"},
    "scout": {"role": "explorer", "host": "native", "use": "Questions"},
}


class AgentConfigTests(HermeticTest):
    def test_defaults_and_escalation_chain(self):
        team = agents.load_agents({"agents": TEAM})
        self.assertEqual("deepseek", agents.default_agent(team, "worker")["name"])
        self.assertEqual("sol", agents.default_agent(team, "reviewer")["name"])  # a lone agent becomes the default
        self.assertEqual(["deepseek", "luna-max", "opus-worker"], agents.escalation_chain(team, "deepseek"))
        self.assertEqual("worker", agents.default_agent({}, "worker")["name"])

    def test_invalid_configurations(self):
        cases = [
            ({"worker": {"role": "worker"}}, "bare role name"),
            ({"a": {"role": "boss"}}, "role must be"),
            ({"a": {"role": "worker", "host": "gemini"}}, "host must be"),
            ({"a": {"role": "worker", "host": "native", "model": "x"}}, "cannot pin a model"),
            ({"a": {"role": "worker", "default": True}, "b": {"role": "worker", "default": True}}, "more than one default"),
            ({"a": {"role": "worker", "escalateTo": "r"}, "r": {"role": "reviewer"}}, "another worker"),
            ({"a": {"role": "worker", "escalateTo": "b"}, "b": {"role": "worker", "escalateTo": "a"}}, "cycle"),
            ({"a": {"role": "worker", "host": "opencode", "model": "x"}}, "provider/model"),
            ({"a": {"role": "worker", "model": "--x", "host": "codex"}}, "invalid model"),
        ]
        for config, message in cases:
            with self.subTest(message=message), self.assertRaisesRegex(HelperError, message):
                agents.load_agents({"agents": config})

    def test_sync_pins_models_and_skips_profile_agents(self):
        repo = self.make_repo()
        team = agents.load_agents({"agents": TEAM})
        outcome = agents.sync(repo, team)
        codex = repo / ".codex" / "agents"
        claude = repo / ".claude" / "agents"
        luna = (codex / "lemmings-luna-max.toml").read_text(encoding="utf-8")
        self.assertIn('model = "gpt-5.6-luna"', luna)
        self.assertIn('model_reasoning_effort = "max"', luna)
        self.assertIn('sandbox_mode = "workspace-write"', luna)
        self.assertIn("Use for: Hard changes", luna)
        self.assertIn('sandbox_mode = "read-only"', (codex / "lemmings-sol.toml").read_text(encoding="utf-8"))
        self.assertIn("model: opus", (claude / "lemmings-opus-worker.md").read_text(encoding="utf-8"))
        self.assertFalse((codex / "lemmings-deepseek.toml").exists())  # profile agents go through dispatch
        self.assertTrue((codex / "lemmings-scout.toml").exists() and (claude / "lemmings-scout.md").exists())
        self.assertEqual([], agents.sync(repo, team, check=True)["stale"])
        self.assertEqual(5, len(outcome["written"]))

    def test_sync_removes_stale_and_never_touches_user_files(self):
        repo = self.make_repo()
        agents.sync(repo, agents.load_agents({"agents": TEAM}))
        user = repo / ".claude" / "agents" / "lemmings-mine.md"
        user.write_text("my own agent", encoding="utf-8")
        smaller = {name: value for name, value in TEAM.items() if name != "scout"}
        outcome = agents.sync(repo, agents.load_agents({"agents": smaller}))
        self.assertEqual(2, len(outcome["removed"]))
        self.assertTrue(user.exists())
        clash = {"mine": {"role": "worker", "host": "claude", "model": "opus"}}
        with self.assertRaisesRegex(HelperError, "not generated by Lemmings"):
            agents.sync(repo, agents.load_agents({"agents": clash}))

    def test_agent_files_are_valid_toml(self):
        repo = self.make_repo()
        agents.sync(repo, agents.load_agents({"agents": TEAM}))
        for path in (repo / ".codex" / "agents").glob("*.toml"):
            self.assertTrue(tomllib.loads(path.read_text(encoding="utf-8"))["developer_instructions"].strip())

    def test_describe(self):
        rows = {row["name"]: row for row in agents.describe(agents.load_agents({"agents": TEAM}))}
        self.assertIsNone(rows["deepseek"]["nativeSubagent"])
        self.assertEqual("lemmings-luna-max", rows["luna-max"]["nativeSubagent"])
        self.assertEqual(["luna-max", "opus-worker"], rows["luna-max"]["escalation"])
