import tomllib

from support import HermeticTest

from lemmings import agents
from lemmings.gitutil import HelperError

TEAM = {
    "deepseek": {"role": "worker", "host": "codex", "profile": "byteplus", "model": "deepseek-v4-pro",
                 "use": "Routine implementation", "default": True, "escalateTo": "luna-max"},
    "luna-max": {"role": "worker", "host": "codex", "model": "gpt-5.6-luna", "effort": "max",
                 "use": "Hard changes", "escalateTo": "opus-worker"},
    "opus-worker": {"role": "worker", "host": "claude", "model": "opus"},
    "sol": {"role": "reviewer", "host": "codex", "model": "gpt-5.6-sol", "effort": "high"},
    "scout": {"role": "explorer", "host": "native", "use": "Questions"},
}


def team(extra=None):
    return agents.load_agents({"defaults": False, "agents": {**TEAM, **(extra or {})}})


class AgentConfigTests(HermeticTest):
    def test_defaults_and_escalation_chain(self):
        configured = team()
        self.assertEqual("deepseek", agents.default_agent(configured, "worker")["name"])
        self.assertEqual("sol", agents.default_agent(configured, "reviewer")["name"])  # a lone agent becomes the default
        self.assertEqual(["deepseek", "luna-max", "opus-worker"], agents.escalation_chain(configured, "deepseek"))
        self.assertEqual("worker", agents.default_agent({}, "worker")["name"])

    def test_invalid_configurations(self):
        cases = [
            ({"worker": {"role": "worker"}}, "bare role name"),
            ({"a": {"role": "boss"}}, "role must be"),
            ({"a": {"role": "worker", "host": "gemini"}}, "host must be"),
            ({"a": {"role": "worker", "host": "native", "model": "x"}}, "cannot pin a model"),
            ({"a": {"role": "worker", "default": True}, "b": {"role": "worker", "default": True}}, "more than one default"),
            ({"a": {"role": "worker", "escalateTo": "r"}, "r": {"role": "reviewer"}}, "another worker"),
            ({"a": {"role": "worker", "escalateTo": "b"}, "b": {"role": "worker", "escalateTo": "a"}}, "cycle"),
            ({"a": {"role": "worker", "host": "opencode", "model": "x"}}, "provider/model"),
            ({"a": {"role": "worker", "model": "--x", "host": "codex"}}, "invalid model"),
        ]
        for config, message in cases:
            with self.subTest(message=message), self.assertRaisesRegex(HelperError, message):
                agents.load_agents({"defaults": False, "agents": config})

    def test_sync_pins_models_and_skips_profile_agents(self):
        repo = self.make_repo()
        configured = team()
        outcome = agents.sync(repo, configured)
        codex = repo / ".codex" / "agents"
        claude = repo / ".claude" / "agents"
        luna = (codex / "lemmings-luna-max.toml").read_text(encoding="utf-8")
        self.assertIn('model = "gpt-5.6-luna"', luna)
        self.assertIn('model_reasoning_effort = "max"', luna)
        self.assertIn('sandbox_mode = "workspace-write"', luna)
        self.assertIn("Use for: Hard changes", luna)
        self.assertIn('sandbox_mode = "read-only"', (codex / "lemmings-sol.toml").read_text(encoding="utf-8"))
        self.assertIn("model: opus", (claude / "lemmings-opus-worker.md").read_text(encoding="utf-8"))
        self.assertFalse((codex / "lemmings-deepseek.toml").exists())  # profile agents go through dispatch
        self.assertTrue((codex / "lemmings-scout.toml").exists() and (claude / "lemmings-scout.md").exists())
        self.assertEqual([], agents.sync(repo, configured, check=True)["stale"])
        self.assertEqual(5, len(outcome["written"]))

    def test_sync_removes_stale_and_never_touches_user_files(self):
        repo = self.make_repo()
        agents.sync(repo, team())
        user = repo / ".claude" / "agents" / "lemmings-mine.md"
        user.write_text("my own agent", encoding="utf-8")
        smaller = {name: value for name, value in TEAM.items() if name != "scout"}
        outcome = agents.sync(repo, agents.load_agents({"defaults": False, "agents": smaller}))
        self.assertEqual(2, len(outcome["removed"]))
        self.assertTrue(user.exists())
        clash = {"mine": {"role": "worker", "host": "claude", "model": "opus"}}
        with self.assertRaisesRegex(HelperError, "not generated by Lemmings"):
            agents.sync(repo, agents.load_agents({"defaults": False, "agents": clash}))

    def test_agent_files_are_valid_toml(self):
        repo = self.make_repo()
        agents.sync(repo, team())
        for path in (repo / ".codex" / "agents").glob("*.toml"):
            self.assertTrue(tomllib.loads(path.read_text(encoding="utf-8"))["developer_instructions"].strip())

    def test_describe(self):
        rows = {row["name"]: row for row in agents.describe(team())}
        self.assertIsNone(rows["deepseek"]["nativeSubagent"])
        self.assertEqual("lemmings-luna-max", rows["luna-max"]["nativeSubagent"])
        self.assertEqual(["luna-max", "opus-worker"], rows["luna-max"]["escalation"])


class ShippedDefaultTests(HermeticTest):
    def test_each_host_has_its_own_defaults_and_escalation(self):
        shipped = agents.load_agents({})
        codex = {role: agents.default_agent(shipped, role, "codex") for role in agents.ROLES}
        claude = {role: agents.default_agent(shipped, role, "claude") for role in agents.ROLES}
        self.assertEqual(("codex-worker", "gpt-5.6-luna"), (codex["worker"]["name"], codex["worker"]["model"]))
        self.assertEqual("gpt-5.6-sol", codex["reviewer"]["model"])
        self.assertEqual(("claude-worker", "sonnet"), (claude["worker"]["name"], claude["worker"]["model"]))
        self.assertEqual("opus", claude["reviewer"]["model"])
        self.assertEqual(["codex-worker", "codex-worker-strong"], agents.escalation_chain(shipped, "codex-worker"))
        self.assertEqual(["claude-worker", "claude-worker-strong"], agents.escalation_chain(shipped, "claude-worker"))
        for agent in shipped.values():
            self.assertEqual([agent["host"]], agent["for"])  # a host never depends on the other CLI

    def test_project_default_replaces_shipped_default_for_its_hosts(self):
        merged = agents.load_agents({"agents": {
            "deepseek": {"role": "worker", "for": ["codex"], "host": "codex", "profile": "byteplus",
                         "model": "deepseek-v4-pro", "default": True, "escalateTo": "codex-worker-strong"}}})
        self.assertEqual("deepseek", agents.default_agent(merged, "worker", "codex")["name"])
        self.assertEqual("claude-worker", agents.default_agent(merged, "worker", "claude")["name"])
        self.assertEqual(["deepseek", "codex-worker-strong"], agents.escalation_chain(merged, "deepseek"))

    def test_project_overrides_by_name_and_can_drop_defaults(self):
        merged = agents.load_agents({"agents": {"claude-reviewer": {"role": "reviewer", "for": ["claude"],
                                                                     "host": "claude", "model": "fable"}}})
        self.assertEqual("fable", merged["claude-reviewer"]["model"])
        self.assertEqual("claude-reviewer", agents.default_agent(merged, "reviewer", "claude")["name"])
        self.assertEqual({}, agents.load_agents({"defaults": False}))

    def test_sync_writes_the_shipped_agents(self):
        repo = self.make_repo()
        agents.sync(repo, agents.load_agents({}))
        codex = sorted(path.name for path in (repo / ".codex" / "agents").iterdir())
        claude = sorted(path.name for path in (repo / ".claude" / "agents").iterdir())
        self.assertEqual(["lemmings-codex-explorer.toml", "lemmings-codex-reviewer.toml",
                          "lemmings-codex-worker-strong.toml", "lemmings-codex-worker.toml"], codex)
        self.assertEqual(["lemmings-claude-explorer.md", "lemmings-claude-reviewer.md",
                          "lemmings-claude-worker-strong.md", "lemmings-claude-worker.md"], claude)
