"""Named agents: which model plays which role, what each is good at, and who takes over on failure.

`.agents/lemmings.json` → `agents` maps a name to a route. The manager picks agents by their
`use` text; `default` marks the role's first choice; `escalateTo` names the stronger agent that
takes over when the manager decides the current one cannot finish the task.
"""
from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Any, Mapping

from .gitutil import HelperError

ROLES = ("worker", "reviewer", "explorer")
HOSTS = ("native", "codex", "claude", "opencode")
NAME = re.compile(r"[a-z0-9]+(?:-[a-z0-9]+)*")
ROLE_TEMPLATES = Path(__file__).resolve().parents[2] / "roles"
GENERATED = "Generated by `lemmings agents sync` from .agents/lemmings.json; edit that file instead."


def load_agents(config: Mapping[str, Any]) -> dict[str, dict[str, Any]]:
    """Validated agents. Every role without a configured agent gets its native default."""
    raw = config.get("agents") or {}
    if not isinstance(raw, Mapping):
        raise HelperError("agents must be an object of name -> agent")
    agents: dict[str, dict[str, Any]] = {}
    for name, value in raw.items():
        if not NAME.fullmatch(name) or name in ROLES:
            raise HelperError(f"agent name {name!r} must be lowercase-hyphenated and not a bare role name")
        if not isinstance(value, Mapping) or value.get("role") not in ROLES:
            raise HelperError(f"agent {name}: role must be one of {', '.join(ROLES)}")
        agent = {"name": name, "host": "native", **value}
        if agent["host"] not in HOSTS:
            raise HelperError(f"agent {name}: host must be one of {', '.join(HOSTS)}")
        for key in ("model", "effort", "profile"):
            if str(agent.get(key) or "").startswith("-"):
                raise HelperError(f"agent {name}: invalid {key}")
        if agent["host"] == "native" and (agent.get("model") or agent.get("effort")):
            raise HelperError(f"agent {name}: a native agent cannot pin a model; name the host (codex or claude) instead")
        if agent["host"] == "opencode" and agent.get("model") and "/" not in agent["model"]:
            raise HelperError(f"agent {name}: OpenCode models use provider/model")
        for item in agent.get("fallback") or []:
            if not isinstance(item, Mapping) or item.get("host") not in HOSTS[1:]:
                raise HelperError(f"agent {name}: each fallback needs host codex, claude, or opencode")
        agents[name] = agent
    for role in ROLES:
        defaults = [name for name, agent in agents.items() if agent["role"] == role and agent.get("default")]
        if len(defaults) > 1:
            raise HelperError(f"role {role} has more than one default agent: {', '.join(defaults)}")
        if not defaults:
            members = [name for name, agent in agents.items() if agent["role"] == role]
            if len(members) == 1:
                agents[members[0]]["default"] = True
    for name, agent in agents.items():
        target = agent.get("escalateTo")
        if target is None:
            continue
        if target not in agents or agents[target]["role"] != agent["role"]:
            raise HelperError(f"agent {name}: escalateTo must name another {agent['role']} agent")
        escalation_chain(agents, name)
    return agents


def escalation_chain(agents: Mapping[str, Mapping[str, Any]], name: str) -> list[str]:
    chain = [name]
    while agents[chain[-1]].get("escalateTo"):
        following = agents[chain[-1]]["escalateTo"]
        if following in chain:
            raise HelperError(f"escalation cycle: {' -> '.join(chain + [following])}")
        chain.append(following)
    return chain


def default_agent(agents: Mapping[str, Mapping[str, Any]], role: str) -> dict[str, Any]:
    for agent in agents.values():
        if agent["role"] == role and agent.get("default"):
            return dict(agent)
    return {"name": role, "role": role, "host": "native", "default": True}


def native_name(agent: Mapping[str, Any]) -> str:
    """The subagent name a host uses for this agent."""
    return "lemmings-" + agent["name"]


def runs_natively_on(agent: Mapping[str, Any], host: str) -> bool:
    """Whether a manager on `host` starts this agent as its own subagent (else it uses dispatch).

    A Codex profile selects another provider configuration, which only `codex exec --profile` applies.
    """
    return agent["host"] == "native" or (agent["host"] == host and host in ("codex", "claude") and not agent.get("profile"))


def _template(role: str) -> tuple[dict[str, str], str]:
    text = (ROLE_TEMPLATES / f"{role}.md").read_text(encoding="utf-8")
    _, front, body = text.split("---", 2)
    meta = {key.strip(): value.strip() for key, value in (line.split(":", 1) for line in front.strip().splitlines())}
    return meta, body.strip()


def render_claude(role: str, name: str, description: str, model: str | None = None, note: str | None = None) -> str:
    meta, body = _template(role)
    lines = ["---", f"name: {name}", f"description: {description}", f"tools: {meta['tools']}"]
    if model:
        lines.append(f"model: {model}")
    lines += ["---", ""]
    if note:
        lines += [f"<!-- {note} -->", ""]
    return "\n".join(lines) + body + "\n"


def render_codex(role: str, name: str, description: str, model: str | None = None, effort: str | None = None,
                 note: str | None = None) -> str:
    meta, body = _template(role)
    writes = "Edit" in meta["tools"]
    lines = [f"# {note}"] if note else []
    lines += [f"name = {json.dumps(name)}", f"description = {json.dumps(description)}",
              f"sandbox_mode = {json.dumps('workspace-write' if writes else 'read-only')}"]
    if model:
        lines.append(f"model = {json.dumps(model)}")
    if effort:
        lines.append(f"model_reasoning_effort = {json.dumps(effort)}")
    return "\n".join(lines) + f'\ndeveloper_instructions = """\n{body}\n"""\n'


def _description(agent: Mapping[str, Any]) -> str:
    text = _template(agent["role"])[0]["description"]
    return f"{text} Use for: {agent['use']}" if agent.get("use") else text


def planned_files(repo: Path, agents: Mapping[str, Mapping[str, Any]]) -> dict[Path, str]:
    """Native subagent definitions for every named agent that runs on Codex or Claude Code."""
    files: dict[Path, str] = {}
    for agent in agents.values():
        name, description = native_name(agent), _description(agent)
        if runs_natively_on(agent, "codex"):
            files[repo / ".codex" / "agents" / f"{name}.toml"] = render_codex(
                agent["role"], name, description, agent.get("model"), agent.get("effort"), GENERATED)
        if runs_natively_on(agent, "claude"):
            files[repo / ".claude" / "agents" / f"{name}.md"] = render_claude(
                agent["role"], name, description, agent.get("model"), GENERATED)
    return files


def sync(repo: Path, agents: Mapping[str, Mapping[str, Any]], check: bool = False) -> dict[str, list[str]]:
    """Write (or with check=True, compare) generated agent files and remove stale generated ones."""
    wanted = planned_files(repo, agents)
    written, stale, removed = [], [], []
    for path, text in wanted.items():
        current = path.read_text(encoding="utf-8") if path.is_file() else None
        if current == text:
            continue
        if current is not None and GENERATED not in current:
            raise HelperError(f"{path} exists and was not generated by Lemmings; rename the agent or remove the file")
        stale.append(str(path))
        if not check:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(text, encoding="utf-8", newline="\n")
            written.append(str(path))
    for directory, pattern in ((repo / ".codex" / "agents", "lemmings-*.toml"), (repo / ".claude" / "agents", "lemmings-*.md")):
        for path in directory.glob(pattern) if directory.is_dir() else []:
            if path not in wanted and GENERATED in path.read_text(encoding="utf-8", errors="replace"):
                stale.append(str(path))
                if not check:
                    path.unlink()
                    removed.append(str(path))
    return {"written": written, "removed": removed, "stale": [] if not check else stale}


def describe(agents: Mapping[str, Mapping[str, Any]]) -> list[dict[str, Any]]:
    rows = []
    for role in ROLES:
        members = [agent for agent in agents.values() if agent["role"] == role] or [default_agent(agents, role)]
        for agent in members:
            rows.append({**{key: agent.get(key) for key in ("name", "role", "host", "model", "effort", "profile", "use")},
                         "default": bool(agent.get("default")),
                         "escalation": escalation_chain(agents, agent["name"]) if agent["name"] in agents else [agent["name"]],
                         "nativeSubagent": (native_name(agent) if agent["name"] in agents else f"lemmings-{role}")
                         if runs_natively_on(agent, "codex") or runs_natively_on(agent, "claude") else None})
    return rows
